apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgvector.fullname" . }}
  labels:
    {{- include "pgvector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pgvector.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
